### ISSUE TITLE
Widevinecdm plugin

### ISSUE THREAD

**Issue by jMavarez** [jMavarez/Tana#3]
Widevine plugin not working on ~~Windows~~ any OS. Can't find widevinecdm plugin for current Chrome version of Electron.

**Edit**: Moved to npm package 'electron-widevinecdm', but it does not provide the correct widevinecdm plugin for the current Chrome version of Electron.

**Comment by jMavarez** [comment]
I'm gonna try to find the correct binaries for Electron's Chrome version 59.0.3071.115 for each OS, zip them, upload them to Drive and download it on project as a postinstall script.

**Comment by yoannmoinet** [comment]
Hi there, awesome project you have here!

Have a look at this issue I've created, https://github.com/electron/electron/issues/12427 it will explain more on this issue !

**Comment by jMavarez** [comment]
This might be working again on Electron v3. (Just tested branch v3-cdm of this [repo](https://github.com/steverandy/electron-quick-start/)). I'll be working again on this project very soon. (Need my Netflix while working)
