### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [jMavarez/Tana#7]
Hi, can I contribute by designing a logo for Tana?

**Comment by jMavarez** [comment]
Sure! That would be awesome!

**Comment by jMavarez** [comment]
@ssnjrthegr8 Any progress with the logo?

**Comment by ssnjrthegr8** [comment]
I apologise for the delay :) I am not getting any great ideas... I have been trying though. I am pretty sure that I can create something good. Also if you have any ideas or any design elements that you want, feel free to tell me. BTW Can you help me by answering a few questions? Like why did you name the project 'tana'? Is there any meaning behind the name?

**Comment by jMavarez** [comment]
The name 'Tana' comes from the word 'Ventana' in Spanish, which means window (I just took a few letters off). The only idea I have is that logo should be simple I guess, pretty straight forward.

**Comment by ssnjrthegr8** [comment]
![text3277](https://user-images.githubusercontent.com/38104354/40871812-8edc0d40-6660-11e8-943e-463fae9201db.png)

How does this look? Shows the transition of a normal window into PiP mode.

**Comment by amiceli** [comment]
nice !

**Comment by jMavarez** [comment]
Looks awesome!! Don't know how the two windows would look as the app icon. But great design, really like it!

**Comment by ssnjrthegr8** [comment]
>Don't know how the two windows would look as the app icon.

It would look kinda like this: 

![g1081](https://user-images.githubusercontent.com/38104354/40899432-8edc87a4-67e4-11e8-8f8e-bd7c379eff78.png)

**Comment by jMavarez** [comment]
Awesome! Can I get a high-res 1024x1024 PNGs of each version to test it on the app?.

**Love the blue color.**

**Comment by ssnjrthegr8** [comment]
![g1081-5](https://user-images.githubusercontent.com/38104354/40979528-af9a2694-68f3-11e8-9bec-e996a8f9f6bf.png)
![g1062-1](https://user-images.githubusercontent.com/38104354/40979529-b0094a56-68f3-11e8-8075-4c4d8812b041.png)

Will this be enough?

**Comment by jMavarez** [comment]
Perfect! After work, I'll add it to the project. I'll post a few screenshots later.

**Comment by ssnjrthegr8** [comment]
Awesome! I will give you all the required files.

**Comment by ssnjrthegr8** [comment]
![text6523](https://user-images.githubusercontent.com/38104354/41039625-9d4c831e-69b7-11e8-97bf-cc86b99ac49d.png)

Would this logo be enough to represent the project as a whole or should I just use this:

![image](https://user-images.githubusercontent.com/38104354/41039726-ff4b8650-69b7-11e8-996e-931a3582ef6c.png)

**Comment by jMavarez** [comment]
Wow! Really like the colors of the bottom-right item. I was thinking of a dark theme for the UI (Settings, About) Hopefully, I might be getting into that this month (work has been hard these past few weeks). Can we try those as the icon?.

PS: The first image shows a **Tana Concept 1** on the edges, just out of curiosity, are there other concepts you've been working on?

**Comment by jMavarez** [comment]
Sorry, misclick.

**Comment by jMavarez** [comment]
Here are a few screenshots with both icons you've made. What you think @ssnjrthegr8 ?
#### Tana Circle Icon
![screenshot_4](https://user-images.githubusercontent.com/1004242/41041780-6ac024aa-6976-11e8-983d-a20f01215ac7.png)
![screenshot_7](https://user-images.githubusercontent.com/1004242/41041786-6f970746-6976-11e8-8244-40d845c45c74.png)
#### Tana Square Icon
![screenshot_5](https://user-images.githubusercontent.com/1004242/41041788-713c158c-6976-11e8-8f18-c6e153181768.png)
![screenshot_6](https://user-images.githubusercontent.com/1004242/41041791-73b1889c-6976-11e8-992a-faefb8b72bca.png)

**Comment by ssnjrthegr8** [comment]
Hmm... Looks better than I expected. Although it's not easily distinguishable right? I think it should be implemented without the background like this: What do you say?
![g9536-0](https://user-images.githubusercontent.com/38104354/41050873-3a3ed298-69d2-11e8-9406-86845555fa6c.png)
![g15767-6](https://user-images.githubusercontent.com/38104354/41050874-3a92d2e4-69d2-11e8-9cb3-b852d54636f5.png)
![g9536-0-0](https://user-images.githubusercontent.com/38104354/41050876-3adc2a84-69d2-11e8-8360-d87b8059b49c.png)
![g16064](https://user-images.githubusercontent.com/38104354/41050877-3b1e6c3c-69d2-11e8-9f07-6e18922d011e.png)

**Comment by ssnjrthegr8** [comment]
> PS: The first image shows a Tana Concept 1 on the edges, just out of curiosity, are there other concepts you've been working on?

Yeah tbh they were all too simple or they sucked :P

**Comment by jMavarez** [comment]
> Hmm... Looks better than I expected. Although it's not easily distinguishable right? I think it should be implemented without the background like this: What do you say?

Yeah, it's not easily distinguishable... Looks better without the background, at least for the icon of the extension and tray.

> Yeah tbh they were all too simple or they sucked :P

It's ok, just being curious.

**Comment by ssnjrthegr8** [comment]
More previews:

![fhdf](https://user-images.githubusercontent.com/38104354/41051278-4685aff8-69d3-11e8-9495-187875a11925.png)
![gkgk](https://user-images.githubusercontent.com/38104354/41051280-46de5b44-69d3-11e8-965f-6008a5f8b606.png)

**Comment by jMavarez** [comment]
Loving this one so far.
![image](https://user-images.githubusercontent.com/1004242/41051376-57bcd59a-698c-11e8-93c3-b9f4d434eb31.png)

**Comment by ssnjrthegr8** [comment]
Great! So I guess I can wrap things up in here by providing you with the files. Is there anything else that you need?

**Comment by jMavarez** [comment]
No, nothing to add! Great design, thank you so much! Send the files whenever you're ready. I'll update the README and give you credit for the logo.

**Comment by ssnjrthegr8** [comment]
Here is the link to the files: https://drive.google.com/open?id=1t45aV1AGrqO6eoWVIs-20Ti1nDy07X3S
It was awesome contributing to this project! Thank you for the opportunity.

**Comment by ssnjrthegr8** [comment]
Also if you wanted the font I have used its Nexa: https://www.fontfabric.com/nexa-free-font/
